# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import log_pb2 as log__pb2


class LogStub(object):
    """定义服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushLog = channel.unary_unary(
                '/pb.Log/PushLog',
                request_serializer=log__pb2.LogRequest.SerializeToString,
                response_deserializer=log__pb2.LogResponse.FromString,
                )


class LogServicer(object):
    """定义服务
    """

    def PushLog(self, request, context):
        """推送日志
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushLog': grpc.unary_unary_rpc_method_handler(
                    servicer.PushLog,
                    request_deserializer=log__pb2.LogRequest.FromString,
                    response_serializer=log__pb2.LogResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pb.Log', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Log(object):
    """定义服务
    """

    @staticmethod
    def PushLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pb.Log/PushLog',
            log__pb2.LogRequest.SerializeToString,
            log__pb2.LogResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
