name: auto update codegen

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "**/*.proto"

jobs:
  code-gen-ts:
    uses: ./.github/workflows/code-gen-ts.yml
  code-gen-py:
    uses: ./.github/workflows/code-gen-py.yml
  code-gen-go:
    uses: ./.github/workflows/code-gen-go.yml

  after-codegen:
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    needs: [code-gen-ts, code-gen-py, code-gen-go]
    strategy:
      # 避免并发请求触发Github的API速率限制
      max-parallel: 1
      matrix:
        include:
          - { repo: 'cookie-fetcher', base_branch: 'master', submodule_path: './ceobe_grpc', need_job: 'code-gen-ts', codegen_branch: 'ts-code-gen' }
          - { repo: 'cookie-analyzer', base_branch: 'master', submodule_path: './ceobe_grpc', need_job: 'code-gen-ts', codegen_branch: 'ts-code-gen' }
    steps:
      - uses: actions/checkout@v3
      - name: 输出调试信息
        uses: actions/github-script@v6
        with:
          script: |
            if ('${{ needs[matrix.need_job].outputs.pushed }}' == 'true') {
              console.log('${{ matrix.need_job }}成功推送了代码生成更新，尝试创建PR');
            } else {
              console.log('${{ matrix.need_job }}未能成功推送代码生成更新，不执行创建PR的步骤');
            }
      - name: 尝试创建PR
        if: ${{ needs[matrix.need_job].outputs.pushed }} == 'true'
        uses: ./.github/workflows/create-pr
        with:
          repo: ${{ matrix.repo }}
          base_branch: ${{ matrix.base_branch }}
          submodule_path: ${{ matrix.submodule_path }}
          codegen_branch: ${{ matrix.codegen_branch }}
          token: ${{ secrets.ACCESS_OTHER_REPO_TOKEN }}



