name: auto update codegen

on:
  workflow_dispatch:
  push:
    branches: [ auto-update-codegen ]
#    paths:
#      - "**/*.proto"

jobs:
  check-cache:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.check-proto-cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Cache
        id: check-proto-cache
        uses: actions/cache@v3
        with:
          path: '__proto_hash__'
          key: proto-${{ hashFiles('**/*.proto') }}
      - run: echo "cache-hit=${{ steps.check-proto-cache.outputs.cache-hit }}" >> "$GITHUB_OUTPUT"
      - run: echo "${{ hashFiles('**/*.proto') }}" > __proto_hash__
  code-gen-ts:
    needs: check-cache
    if: needs.check-cache.outputs.cache-hit != 'true'
    uses: ./.github/workflows/code-gen-ts.yml
  code-gen-py:
    needs: check-cache
    if: needs.check-cache.outputs.cache-hit != 'true'
    uses: ./.github/workflows/code-gen-py.yml
  code-gen-go:
    needs: check-cache
    if: needs.check-cache.outputs.cache-hit != 'true'
    uses: ./.github/workflows/code-gen-go.yml

  create-pr:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [code-gen-ts, code-gen-py, code-gen-go]
    strategy:
      matrix:
        include:
          - { repo: 'cookie-fetcher', base_branch: 'master', submodule_path: './ceobe_grpc', need_job: 'code-gen-ts' }
    steps:
      - uses: actions/checkout@v3
      - name: 如果依赖任务执行成功则创建PR
        if: needs[matrix.need_job].result == 'success'
        uses: ./.github/workflows/create-pr.yml
      - name: 如果不创建PR，则输出原因
        if: needs[matrix.need_job].result != 'success'
        run: echo '因${{ matrix.need_job }}的执行结果是${{ needs[matrix.need_job].result }}，不执行创建PR的步骤'



