name: ts code generate

on:
  workflow_dispatch:
  workflow_call:

jobs:
  code-gen-ts:
    runs-on: ubuntu-latest

    steps:
      # set up toolchain
      - name: Setup protoc
        uses: arduino/setup-protoc@v2
        with:
          version: "24.x"
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      # 给当前服务器安装node
      - name: set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18 # node版本

      # 分别checkout master和ts-code-gen分支
      - name: checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          path: ./master

      - name: Checkout ts-code-gen branch
        uses: actions/checkout@v3
        with:
          ref: ts-code-gen
          path: ./ts-code-gen

      # 清理workflow文件
      - name: remove old gen files
        run: |
          rm -rf ./ts-code-gen/.github

      - run: npm ci
        working-directory: ./master/scripts/node

      # 生成代码
      - name: generate proto code
        run: npm run codegen ${{ github.workspace }}/master ${{ github.workspace }}/ts-code-gen
        working-directory: ./master/scripts/node

      - name: read old codegen info
        id: old-codegen-info
        working-directory: ./ts-code-gen
        # 因为一开始没有这个文件，所以写入一段空内容
        run: |
          echo "" >> ./codegen_info
          cat ./codegen_info >> "$GITHUB_OUTPUT"

      - name: write codegen info
        working-directory: ./master
        run: |
          echo "CURRENT_MASTER_SHA=$(git rev-parse --short HEAD)" >> ../ts-code-gen/codegen_info
          echo "LAST_MASTER_SHA=${{ steps.old-codegen-info.outputs.CURRENT_MASTER_SHA }}" >> ../ts-code-gen/codegen_info

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '[CI] update ts-code-gen'
          cwd: ./ts-code-gen
