name: go code generate

on:
  workflow_dispatch:
  workflow_call:

jobs:
  code-gen-go:
    runs-on: ubuntu-latest

    steps:
      # set up toolchain
      - name: Setup protoc
        uses: arduino/setup-protoc@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go environment
        uses: actions/setup-go@v3

      - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2

      # check out master 分支
      - name: check out master
        uses: actions/checkout@v3
        with:
          path: ./master

      # checkout go 分支
      - name: Checkout go branch
        uses: actions/checkout@v3
        with:
          ref: go-code-gen
          path: ./go-code-gen

      # 在master 中生成代码
      - name: generate proto code
        run:
          mkdir -v code_gen &&
          protoc --go_out=./code_gen protos/*.proto &&
          protoc --go-grpc_out=./code_gen protos/*.proto
        working-directory: ./master

      # 清理 go code gen 中的Go文件
      - name: remove old gen files
        run: |
          rm -rf ./go-code-gen/code_gen
          rm -rf ./go-code-gen/protos

      # 移动新生成的文件到 go code gen
      - name: copy origin proto files
        run:
          mkdir -v ./go-code-gen/protos &&
          cp -vr ./master/protos/* ./go-code-gen/protos

      - name: copy code gen
        run:
          mkdir -v ./go-code-gen/code_gen &&
          cp -vr ./master/code_gen/* ./go-code-gen/code_gen

      - name: Add & Commit
        uses: EndBug/add-and-commit@v9.1.1
        with:
          default_author: github_actions
          message: '[CI] update go-code-gen'
          cwd: ./go-code-gen
